; #######################################################################################
; # This Inno Setup script was generated by Visual & Installer for MS Visual Studio     #
; # Visual & Installer (c) 2012 - 2017 unSigned, s. r. o. All Rights Reserved.          #
; # Visit http://www.visual-installer.com/ for more details.                            #
; #######################################################################################

; This script is perhaps one of the simplest Inno Setup installer you can make. 
; All of the optional settings are left to their default settings. 

; See the Inno Setup documentation at http://www.jrsoftware.org/ for details on creating script files!    

;--------------------------------

[Setup]
AppName=RestartCounter
AppVersion=1.0
DefaultDirName={pf}\RestartCounter
DefaultGroupName=RestartCounter
UninstallDisplayIcon={app}\Setup_Inno.exe
Compression=lzma2
SolidCompression=yes

OutputBaseFilename=Setup_Inno

[Files]
Source: "Script.iss"; DestDir: "{app}"
Source: "..\Restarter\bin\Release\Restarter.exe"; DestDir: "{app}"
Source: "..\Restarter\bin\Release\Restarter.exe"; DestDir: "{app}"

[Icons]
Name: "{group}\Setup_Inno"; Filename: "{app}\Setup_Inno.exe"
Name: "{group}\RestartCounter"; Filename: "{app}\Restarter.exe"
Name: "{userdesktop}\RestartCounter"; Filename: "{app}\Restarter.exe"

[Registry]
Root: HKCU; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "RestartCounter"; ValueData: """{app}\Restarter.exe"""; Flags: uninsdeletevalue


[Code]

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usPostUninstall then
  begin
    if RegKeyExists(HKEY_CURRENT_USER, '{SOFTWARE\Microsoft\Windows\CurrentVersion\Run\RestartCounter}') then
      if MsgBox('Do you want to delete the overlay filter registry key ?',
        mbConfirmation, MB_YESNO) = IDYES
      then
        RegDeleteKeyIncludingSubkeys(HKEY_CURRENT_USER, '{SOFTWARE\Microsoft\Windows\CurrentVersion\Run\RestartCounter}');
  end;
end;